'use client'

import { useState, useEffect } from 'react'
import { X, Lock, Globe, ExternalLink, Loader2, CheckCircle2, AlertCircle } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { ProjectFile } from '@/types'

interface GitHubPushModalProps {
  open: boolean
  onClose: () => void
  projectId: string
  projectName: string
  files: ProjectFile[]
  isGitHubConnected: boolean
}

type PushState = 'idle' | 'pushing' | 'success' | 'error'

export function GitHubPushModal({
  open,
  onClose,
  projectId,
  projectName,
  files,
  isGitHubConnected,
}: GitHubPushModalProps) {
  const [repoName, setRepoName] = useState('')
  const [isPrivate, setIsPrivate] = useState(false)
  const [pushState, setPushState] = useState<PushState>('idle')
  const [repoUrl, setRepoUrl] = useState('')
  const [errorMsg, setErrorMsg] = useState('')

  useEffect(() => {
    if (open && projectName) {
      setRepoName(projectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''))
    }
    if (!open) {
      setPushState('idle')
      setRepoUrl('')
      setErrorMsg('')
    }
  }, [open, projectName])

  if (!open) return null

  // Inline GitHub octicon SVG (not in lucide-react)
  const GithubIcon = ({ className }: { className?: string }) => (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
    </svg>
  )

  const handleConnectGitHub = () => {
    window.location.href = `/api/auth/github?projectId=${projectId}`
  }

  const handlePush = async () => {
    if (!repoName.trim()) return
    setPushState('pushing')
    setErrorMsg('')

    try {
      const res = await fetch('/api/github/push', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repoName: repoName.trim(),
          description: `Generated by Code Genesis — ${projectName}`,
          files: files.map((f) => ({ path: f.path, content: f.content })),
          isPrivate,
        }),
      })

      const data = await res.json()

      if (!res.ok) {
        setErrorMsg(data.error ?? 'Push failed')
        setPushState('error')
        return
      }

      setRepoUrl(data.repoUrl)
      setPushState('success')
    } catch {
      setErrorMsg('Network error — check your connection')
      setPushState('error')
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />

      {/* Modal */}
      <div className="relative z-10 w-full max-w-md mx-4 bg-background border border-border rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-zinc-800 flex items-center justify-center">
              <GithubIcon className="w-4 h-4 text-white" />
            </div>
            <div>
              <p className="text-sm font-semibold">Push to GitHub</p>
              <p className="text-xs text-muted-foreground">{files.length} files ready</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-muted transition-colors text-muted-foreground hover:text-foreground"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 space-y-4">
          {!isGitHubConnected ? (
            /* Not connected */
            <div className="text-center space-y-4 py-4">
              <div className="w-14 h-14 rounded-full bg-zinc-800 flex items-center justify-center mx-auto">
                <GithubIcon className="w-7 h-7 text-white" />
              </div>
              <div>
                <p className="font-medium text-sm">Connect your GitHub account</p>
                <p className="text-xs text-muted-foreground mt-1">
                  Authorize Code Genesis to create repositories on your behalf.
                </p>
              </div>
              <button
                onClick={handleConnectGitHub}
                className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-zinc-900 border border-zinc-700 hover:bg-zinc-800 text-white text-sm font-semibold transition-colors"
              >
                <GithubIcon className="w-4 h-4" />
                Connect GitHub
              </button>
            </div>
          ) : pushState === 'success' ? (
            /* Success */
            <div className="text-center space-y-4 py-4">
              <div className="w-14 h-14 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto">
                <CheckCircle2 className="w-7 h-7 text-emerald-400" />
              </div>
              <div>
                <p className="font-semibold text-sm text-emerald-400">Repository created!</p>
                <p className="text-xs text-muted-foreground mt-1">
                  {files.length} files pushed successfully.
                </p>
              </div>
              <a
                href={repoUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                Open Repository
              </a>
              <button
                onClick={onClose}
                className="w-full py-2 text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                Close
              </button>
            </div>
          ) : (
            /* Push form */
            <>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground">Repository name</label>
                <input
                  value={repoName}
                  onChange={(e) =>
                    setRepoName(e.target.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''))
                  }
                  placeholder="my-awesome-app"
                  className="w-full px-3 py-2 rounded-lg border border-border bg-muted/30 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500/50 focus:border-violet-500/50 transition-all font-mono"
                  disabled={pushState === 'pushing'}
                />
              </div>

              <div className="flex gap-2">
                <button
                  onClick={() => setIsPrivate(false)}
                  className={cn(
                    'flex-1 flex items-center gap-2 px-3 py-2 rounded-lg border text-xs font-medium transition-all',
                    !isPrivate
                      ? 'border-violet-500/60 bg-violet-500/10 text-violet-400'
                      : 'border-border text-muted-foreground hover:bg-muted'
                  )}
                >
                  <Globe className="w-3.5 h-3.5" />
                  Public
                </button>
                <button
                  onClick={() => setIsPrivate(true)}
                  className={cn(
                    'flex-1 flex items-center gap-2 px-3 py-2 rounded-lg border text-xs font-medium transition-all',
                    isPrivate
                      ? 'border-violet-500/60 bg-violet-500/10 text-violet-400'
                      : 'border-border text-muted-foreground hover:bg-muted'
                  )}
                >
                  <Lock className="w-3.5 h-3.5" />
                  Private
                </button>
              </div>

              {pushState === 'error' && (
                <div className="flex items-start gap-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-xs text-red-400">
                  <AlertCircle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                  {errorMsg}
                </div>
              )}

              <button
                onClick={handlePush}
                disabled={!repoName.trim() || pushState === 'pushing'}
                className={cn(
                  'w-full flex items-center justify-center gap-2 py-2.5 rounded-xl text-sm font-semibold transition-all',
                  repoName.trim() && pushState !== 'pushing'
                    ? 'bg-zinc-900 border border-zinc-700 hover:bg-zinc-800 text-white'
                    : 'bg-muted text-muted-foreground cursor-not-allowed'
                )}
              >
                {pushState === 'pushing' ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Pushing {files.length} files…
                  </>
                ) : (
                  <>
                    <GithubIcon className="w-4 h-4" />
                    Create & Push Repository
                  </>
                )}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
