import type { RequirementsDoc } from '@/lib/ai/stages/requirements'
import type { ArchitectureDoc } from '@/lib/ai/stages/architecture-doc'
import type { ProjectFile } from '@/types'

// ── Helpers ──────────────────────────────────────────────────────────────────
function today(): string {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function numberedList(items: string[], prefix = ''): string {
  return items.map((it, i) => `${prefix}${i + 1}. ${it}`).join('\n')
}

// ── 1. Software Requirements Specification (SRS) ──────────────────────────────
export function generateSRS(
  doc: RequirementsDoc,
  prompt: string,
  answers: Record<string, string>,
): string {
  const answered = doc.questions
    .map((q, i) => `**${i + 1}. ${q.question}**\n\n> ${answers[q.id]?.trim() || '_Not specified_'}`)
    .join('\n\n')

  return `# Software Requirements Specification (SRS)

**Project:** ${doc.projectName}
**Document Version:** 1.0
**Date:** ${today()}
**Prepared by:** Code Genesis

---

## 1. Introduction

### 1.1 Purpose
This document specifies the software requirements for **${doc.projectName}**. It describes the system's intended functionality, features, and technical constraints to guide design and implementation.

### 1.2 Project Overview
${doc.overview}

### 1.3 Original Request
> ${prompt}

---

## 2. Overall Description

### 2.1 Product Perspective
${doc.projectName} is a web application built with a modern front-end stack. It is designed to be self-contained and runnable in a standard Node.js environment.

### 2.2 Technology Stack
${doc.techStack.map((t) => `- ${t}`).join('\n')}

---

## 3. Functional Requirements

The system shall provide the following core features:

${numberedList(doc.coreFeatures.map((f) => `**${f}** — The system shall implement ${f.toLowerCase()}.`))}

---

## 4. Requirement Clarifications

The following clarifications were gathered during requirements analysis:

${answered || '_No clarifications recorded._'}

---

## 5. Non-Functional Requirements

- **Usability:** The interface shall be responsive and accessible on modern browsers.
- **Performance:** Pages shall load within a reasonable time on a standard connection.
- **Maintainability:** Code shall be written in TypeScript with a clear component structure.
- **Portability:** The application shall run in any standard Node.js / Next.js environment.

---

*Generated by Code Genesis — AI-Powered SDLC IDE*
`
}

// ── 2. Software Design Document (SDD) ─────────────────────────────────────────
export function generateSDD(
  doc: ArchitectureDoc,
  requirements: RequirementsDoc | null,
): string {
  const fileTree = doc.fileTree?.length
    ? doc.fileTree.map((f) => `| \`${f.path}\` | ${f.description} |`).join('\n')
    : '| _No files defined_ | |'

  const components = doc.components?.length
    ? doc.components.map((c) => `### ${c.name}\n- **Type:** ${c.type}\n- **Purpose:** ${c.purpose}`).join('\n\n')
    : '_No components defined._'

  return `# Software Design Document (SDD)

**Project:** ${doc.projectName}
**Document Version:** 1.0
**Date:** ${today()}
**Prepared by:** Code Genesis

---

## 1. Introduction

### 1.1 Purpose
This document describes the software architecture and design for **${doc.projectName}**, translating the requirements into a concrete technical blueprint.

### 1.2 System Summary
${doc.summary}

---

## 2. System Architecture

### 2.1 Technology Stack
${doc.techStack.map((t) => `- ${t}`).join('\n')}

### 2.2 Data Flow
${doc.dataFlow}

---

## 3. File Structure

The system is composed of approximately **${doc.estimatedFiles}** source files:

| File | Responsibility |
|------|----------------|
${fileTree}

---

## 4. Component Design

${components}

---

## 5. Traceability

${requirements?.coreFeatures?.length
      ? `This design satisfies the following requirements:\n\n${requirements.coreFeatures.map((f) => `- ${f}`).join('\n')}`
      : '_Requirements traceability not available._'}

---

*Generated by Code Genesis — AI-Powered SDLC IDE*
`
}

// ── 3. Implementation / Technical Documentation ───────────────────────────────
export function generateImplementationDoc(
  files: ProjectFile[],
  doc: ArchitectureDoc | null,
  projectName: string,
): string {
  const byDir = new Map<string, ProjectFile[]>()
  for (const f of files) {
    const dir = f.path.includes('/') ? f.path.split('/').slice(0, -1).join('/') : '(root)'
    if (!byDir.has(dir)) byDir.set(dir, [])
    byDir.get(dir)!.push(f)
  }

  const fileSections = Array.from(byDir.entries())
    .map(([dir, fs]) => {
      const rows = fs.map((f) => {
        const lines = f.content.split('\n').length
        return `| \`${f.path.split('/').pop()}\` | ${f.language} | ${lines} lines |`
      }).join('\n')
      return `### \`${dir}/\`\n\n| File | Language | Size |\n|------|----------|------|\n${rows}`
    })
    .join('\n\n')

  return `# Implementation Documentation

**Project:** ${projectName}
**Document Version:** 1.0
**Date:** ${today()}
**Prepared by:** Code Genesis

---

## 1. Overview
${doc?.summary ?? `Technical implementation documentation for ${projectName}.`}

This document catalogs the source files produced during the implementation phase.

---

## 2. Project Statistics

- **Total files:** ${files.length}
- **Total lines of code:** ${files.reduce((sum, f) => sum + f.content.split('\n').length, 0)}
- **Tech stack:** ${doc?.techStack?.join(', ') ?? 'Next.js, TypeScript, Tailwind CSS'}

---

## 3. Source File Index

${fileSections || '_No files generated yet._'}

---

## 4. Build & Run

\`\`\`bash
npm install      # install dependencies
npm run dev      # start the development server (http://localhost:3001)
npm run build    # create a production build
\`\`\`

---

*Generated by Code Genesis — AI-Powered SDLC IDE*
`
}

// ── Browser download helper ───────────────────────────────────────────────────
export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
