import type { ProjectFile } from '@/types'

// Returns the minimum scaffold files needed to make a generated Next.js project runnable.
// Only injects files that are NOT already present in the generated set.
export function injectScaffold(files: ProjectFile[]): ProjectFile[] {
  const existing = new Set(files.map((f) => f.path.replace(/^\//, '')))

  const scaffold: { path: string; content: string; language: string }[] = [
    {
      path: 'package.json',
      language: 'json',
      content: JSON.stringify(
        {
          name: 'code-genesis-project',
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev -p 3001',
            build: 'next build',
            start: 'next start -p 3001',
          },
          dependencies: {
            next: '14.2.5',
            react: '^18',
            'react-dom': '^18',
            typescript: '^5',
          },
          devDependencies: {
            '@types/node': '^20',
            '@types/react': '^18',
            '@types/react-dom': '^18',
            autoprefixer: '^10',
            postcss: '^8',
            tailwindcss: '^3',
          },
        },
        null,
        2
      ),
    },
    {
      path: 'next.config.js',
      language: 'javascript',
      content: `const path = require('path')
/** @type {import('next').NextConfig} */
const nextConfig = {
  // Pin the workspace root to THIS folder. Without it, Next.js 15/16 walks up
  // the directory tree, gets confused by the symlinked node_modules, and fails
  // with "Next.js inferred your workspace root, but it may not be correct".
  outputFileTracingRoot: __dirname,
  turbopack: { root: __dirname },
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: true },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'ALLOWALL' },
          { key: 'Content-Security-Policy', value: "frame-ancestors *" },
        ],
      },
    ]
  },
}
module.exports = nextConfig
`,
    },
    {
      path: 'tsconfig.json',
      language: 'json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'es5',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./*'] },
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        },
        null,
        2
      ),
    },
    {
      path: 'tailwind.config.ts',
      language: 'typescript',
      content: `import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}', './app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
}
export default config
`,
    },
    {
      path: 'postcss.config.js',
      language: 'javascript',
      content: `module.exports = {
  plugins: { tailwindcss: {}, autoprefixer: {} },
}
`,
    },
    {
      path: 'app/globals.css',
      language: 'css',
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}
@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}
body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
}
`,
    },
    {
      path: 'app/layout.tsx',
      language: 'typescript',
      content: `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Code Genesis App',
  description: 'Generated by Code Genesis',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    },
  ]

  const toAdd: ProjectFile[] = scaffold
    .filter((s) => !existing.has(s.path))
    .map((s, i) => ({
      id: `scaffold-${i}`,
      path: s.path,
      content: s.content,
      language: s.language,
    }))

  return [...files, ...toAdd]
}
