import { NextRequest, NextResponse } from 'next/server'
import { Octokit } from '@octokit/rest'

export async function POST(req: NextRequest) {
  const token = req.cookies.get('gh_token')?.value
  if (!token) {
    return NextResponse.json({ error: 'Not authenticated with GitHub' }, { status: 401 })
  }

  try {
    const { repoName, description, files, isPrivate } = await req.json()

    if (!repoName?.trim() || !files?.length) {
      return NextResponse.json({ error: 'Missing repoName or files' }, { status: 400 })
    }

    const octokit = new Octokit({ auth: token })

    // Get authenticated user
    const { data: user } = await octokit.rest.users.getAuthenticated()
    const owner = user.login
    const name = repoName.trim().toLowerCase().replace(/\s+/g, '-')

    // ── Get-or-create the repo ──────────────────────────────────────────────
    // Creating unconditionally throws "name already exists" on a second push,
    // so reuse the repo if it's already there and push an update instead.
    let repo
    let created = false
    try {
      repo = (await octokit.rest.repos.get({ owner, repo: name })).data
    } catch (err: unknown) {
      if ((err as { status?: number }).status === 404) {
        repo = (await octokit.rest.repos.createForAuthenticatedUser({
          name,
          description: description ?? 'Generated by Code Genesis',
          private: isPrivate ?? false,
          auto_init: false,
        })).data
        created = true
      } else {
        throw err
      }
    }

    const branch = repo.default_branch || 'main'

    // ── Find the current HEAD (if the repo already has commits) ──────────────
    let parentSha: string | undefined
    let baseTree: string | undefined
    try {
      const ref = await octokit.rest.git.getRef({ owner, repo: repo.name, ref: `heads/${branch}` })
      parentSha = ref.data.object.sha
      const headCommit = await octokit.rest.git.getCommit({ owner, repo: repo.name, commit_sha: parentSha })
      baseTree = headCommit.data.tree.sha
    } catch (err: unknown) {
      // 404/409 = empty repo with no commits yet — first push, no parent.
      if (![404, 409].includes((err as { status?: number }).status ?? 0)) throw err
    }

    // 1. Create a blob for each file
    const blobs = await Promise.all(
      files.map(async (file: { path: string; content: string }) => {
        const { data } = await octokit.rest.git.createBlob({
          owner,
          repo: repo.name,
          content: Buffer.from(file.content).toString('base64'),
          encoding: 'base64',
        })
        return { path: file.path.replace(/^\//, ''), sha: data.sha }
      })
    )

    // 2. Create a tree (layered on the existing one when updating)
    const { data: tree } = await octokit.rest.git.createTree({
      owner,
      repo: repo.name,
      base_tree: baseTree,
      tree: blobs.map(({ path, sha }) => ({
        path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha,
      })),
    })

    // 3. Create the commit (parented on HEAD when updating)
    const { data: commit } = await octokit.rest.git.createCommit({
      owner,
      repo: repo.name,
      message: parentSha
        ? 'Update — pushed by Code Genesis'
        : 'Initial commit — generated by Code Genesis',
      tree: tree.sha,
      parents: parentSha ? [parentSha] : [],
    })

    // 4. Point the branch at the new commit (update if it exists, else create)
    if (parentSha) {
      await octokit.rest.git.updateRef({
        owner, repo: repo.name, ref: `heads/${branch}`, sha: commit.sha, force: true,
      })
    } else {
      await octokit.rest.git.createRef({
        owner, repo: repo.name, ref: `refs/heads/${branch}`, sha: commit.sha,
      })
    }

    return NextResponse.json({
      repoUrl: repo.html_url,
      repoName: repo.full_name,
      filesCount: files.length,
      created,
      updated: !created,
    })
  } catch (err: unknown) {
    console.error('[/api/github/push]', err)
    const message = err instanceof Error ? err.message : 'Push failed'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
