import { NextRequest, NextResponse } from 'next/server'
import { Octokit } from '@octokit/rest'

export async function POST(req: NextRequest) {
  const token = req.cookies.get('gh_token')?.value
  if (!token) {
    return NextResponse.json({ error: 'Not authenticated with GitHub' }, { status: 401 })
  }

  try {
    const { repoName, description, files, isPrivate } = await req.json()

    if (!repoName?.trim() || !files?.length) {
      return NextResponse.json({ error: 'Missing repoName or files' }, { status: 400 })
    }

    const octokit = new Octokit({ auth: token })

    // Get authenticated user
    const { data: user } = await octokit.rest.users.getAuthenticated()

    // Create repository
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName.trim().toLowerCase().replace(/\s+/g, '-'),
      description: description ?? 'Generated by Code Genesis',
      private: isPrivate ?? false,
      auto_init: false,
    })

    // Build a single commit with all files using the Git Data API
    // 1. Create blobs for each file
    const blobs = await Promise.all(
      files.map(async (file: { path: string; content: string }) => {
        const { data } = await octokit.rest.git.createBlob({
          owner: user.login,
          repo: repo.name,
          content: Buffer.from(file.content).toString('base64'),
          encoding: 'base64',
        })
        return { path: file.path.replace(/^\//, ''), sha: data.sha }
      })
    )

    // 2. Create tree
    const { data: tree } = await octokit.rest.git.createTree({
      owner: user.login,
      repo: repo.name,
      tree: blobs.map(({ path, sha }) => ({
        path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha,
      })),
    })

    // 3. Create commit (no parent — first commit)
    const { data: commit } = await octokit.rest.git.createCommit({
      owner: user.login,
      repo: repo.name,
      message: 'Initial commit — generated by Code Genesis',
      tree: tree.sha,
      parents: [],
    })

    // 4. Create main branch ref
    await octokit.rest.git.createRef({
      owner: user.login,
      repo: repo.name,
      ref: 'refs/heads/main',
      sha: commit.sha,
    })

    return NextResponse.json({
      repoUrl: repo.html_url,
      repoName: repo.full_name,
      filesCount: files.length,
    })
  } catch (err: unknown) {
    console.error('[/api/github/push]', err)
    const message = err instanceof Error ? err.message : 'Push failed'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
